OUTPUT_DIR: exp_V+Conv2D-BiLSTM+PHQ-Binary
SAVE_CONFIG_NAME: config_V+Conv2D-BiLSTM+PHQ-Binary.yaml
CKPTS_DIR: E:\myworkspace\hxq_ade\trainer\model_weights  # TODO
TYPE: V+Conv2D-BiLSTM+PHQ-Binary  # TODO
MANUAL_SEED: 1
LOG_TITLE: Depression Detection with visual features (key points & gaze direction), Conv2D-BiLSTM, PHQ-Binary, CrossEntropy with weights, ASAM # TODO

DATA:
  TRAIN_ROOT_DIR: E:\myworkspace\DepressionEstimation\daic_woz_preprocessing\daic_woz_dataset\DAIC_WOZ-generated_database_V2\train\clipped_data\
  VALIDATION_ROOT_DIR: E:\myworkspace\DepressionEstimation\daic_woz_preprocessing\daic_woz_dataset\DAIC_WOZ-generated_database_V2\train\original_data\
  TEST_ROOT_DIR: E:\myworkspace\DepressionEstimation\daic_woz_preprocessing\daic_woz_dataset\DAIC_WOZ-generated_database_V2\test\clipped_data\
  USE_MEL_SPECTROGRAM: False
  VISUAL_WITH_GAZE: True
  PADDING:
  RESCALE_SIZE:
  CROP_SIZE:
  BATCH_SIZE: 500  # TODO
  NUM_WORKERS: 0  # TODO

MODEL:
  PHQ_THRESHOLD: 10
  EPOCHS: 50
  WEIGHTS:
    TYPE: new        # ['new', 'last', 'absolute_path', others custom_type]
    DATE:
    PATH: model_weights
    NAME: 
    CUSTOM_ABSOLUTE_PATH: 
    INCLUDED:
  VISUAL_NET:
    INPUT_DIM: 3
    CONV_HIDDEN: 256
    LSTM_HIDDEN: 256
    OUTPUT_DIM: 256
    NUM_LAYERS: 4
    ACTIVATION: relu  # ['sigmoid', 'softmax', 'global', else]
    NORM: bn          # ['bn', 'wn']: nn.BatchNorm1d, nn.utils.weight_norm
    DROPOUT: 0.5
  EVALUATOR:
    PREDICT_TYPE: phq-binary    # ['phq-subscores', 'phq-score', 'phq-binary']
    INPUT_FEATURE_DIM: 256
    CLASSES_RESOLUTION: 2 
    N_CLASSES: 2
    N_SUBSCORES: 8
    STD: 5
  CRITERION:
    USE_SOFT_LABEL: False
    USE_WEIGHTS: True
  OPTIMIZER:
    LR: 1.0e-3
    WEIGHT_DECAY: 1.0e-4
    USE_SAM: True
  SCHEDULER:
    STEP_SIZE: 10
    GAMMA: 0.90
    


